- hosts: masters
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: true
        owner: ubuntu

    - name: Install pod network
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Get kubeadm join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: true
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Join cluster
      shell: "{{ hostvars['kmaster.nahue.ar'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
